### ISSUE TITLE
Cannot make nelz more than 1

### ISSUE THREAD

**Issue by ysyysy115** [PittAMRL/StressTopOpt#1]
Hi PittAMRL,

Thank you for providing the wonderful stress-TO code. I noticed a problem when I change nelz from 1 to any integer larger than 1.
For example, nelx=80, nely=30, nelz=2 (defined in both Stress_3D_Sensitivity_Comp.m and run_stress_min.m), I got the following error message:

Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for that dimension.

Error in stress_minimize (line 11)
imagesc(reshape(MISES.*(0.5*sign(x-0.5)+0.5),nely,nelx));axis equal;axis off; colormap('jet');title('Von-Mises Stress');colorbar;drawnow;

Error in run_stress_min (line 35)
[f0val,df0dx,fval,dfdx]=stress_minimize(xval,Hs,H);

Could you please help?

Best,
Jason

**Comment by psv4** [comment]
Hi Jason,

Apologies for the delayed response. The imagesc function only takes two dimensional inputs, so that is why `nelz=2` is breaking the code. Could you try commenting out that line and see if the code completes?

Best,
Praveen

**Comment by ysyysy115** [comment]
Hi Praveen,

Thank you for your reply.
I think a new error occurs when the iimagesc is resolved. 
I actually could only use nelx=200; nely=60; nelz=1; which is the default in the code.
Once any number changed, the reshape in Stress_3D_Sensitivity_Comp will make some error.
For example, if 
nelx=100;
nely=60;
nelz=1;
The error message is:
Error using reshape
Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for
that dimension.

Error in Stress_3D_Sensitivity_Comp (line 29)
sK = reshape(KE(:)*(Emin+x(:)'.^pl*(E0-Emin)),24*24*nele,1);

Error in stress_minimize (line 5)
[pnorm,pnorm_sen,MISES]=Stress_3D_Sensitivity_Comp(x,nelx,nely,nelz,pl,q,p);

Error in run_stress_min (line 35)
[f0val,df0dx,fval,dfdx]=stress_minimize(xval,Hs,H);


Best,
Jason

**Comment by psv4** [comment]
Hello Jason,

There were also domain sizes defined in `stress_minimize` which was causing that issue. I removed the fixed variables and made the domain arguments to the function. Along with that, I enforced the stress plot to show the first z-layer similar to the material plot. That should fix the original issue as well. PR #2 .

Close the issue if that helps :)

Best,
Praveen

**Comment by ysyysy115** [comment]
Hi Praveen,

Thank you for you prompt response and clarification! This does help. I close the issue.

Best,
Jason
